sound/misc/monsterkill1.wav
sound/misc/multikill1.wav
sound/misc/ultrakill1.wav
sound/misc/killingspree1.wav
sound/misc/melodie.wav
sound/misc/megakill1.wav
sound/misc/perfect.wav
sound/misc/unstoppable1.wav
sound/misc/rampage1.wav
sound/misc/dominating1.wav
sound/misc/combowhore1.wav
sound/misc/godlike1.wav
sound/misc/firstblood1.wav
sound/misc/realnet.jpg
sound/misc/feelgood.wav
sound/misc/pusbomba.wav
sound/misc/gasitbomba.wav
sound/misc/scapatbomba.wav
sound/misc/20sec.wav
sound/misc/30sec.wav
maps/awp_metro.res