//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  : cs_horsewhisperer
//
// Download @: http://dwl.17buddies.net/link/map/1565/cs_horsewhisperer.html
//
//////////////////////////////////////////////////////////
 
gfx/env/desup.tga
gfx/env/desdn.tga
gfx/env/deslf.tga
gfx/env/desrt.tga
gfx/env/desft.tga
gfx/env/desbk.tga

sound/ambience/cricket.wav
