gfx/env/hilltownbk.tga
gfx/env/hilltowndn.tga
gfx/env/hilltownft.tga
gfx/env/hilltownlf.tga
gfx/env/hilltownrt.tga
gfx/env/hilltownup.tga
maps/cs_hilltown.bsp
maps/cs_hilltown.txt
maps/cs_hilltown.res
models/coldshell/jeep-russian.mdl
models/coldshell/pallet_stack.mdl
models/costabrava/wb_seat.mdl
models/costabrava/wb_table01.mdl
models/costabrava/wb_umbrella.mdl
models/cs_paris/cs_paris_fass.mdl
models/cs_psychobilly/tree4.mdl
models/de_plaka/plaka_car1.mdl
models/de_plaka/plaka_car3.mdl
models/de_plaka/plaka_tree1.mdl
models/dustman/radiator.mdl
models/golf.mdl
overviews/cs_hilltown.bmp
overviews/cs_hilltown.txt
sprites/cof.spr