gfx/env/arcdup.tga
gfx/env/arcddn.tga
gfx/env/arcdlf.tga
gfx/env/arcdrt.tga
gfx/env/arcdft.tga
gfx/env/arcdbk.tga
models/scientist.mdl
models/hostage.mdl
sound/ambience/wind2.wav
sound/ambience/wind1.wav
sound/ambience/3dmeagle.wav
sound/ambience/rascheln.wav
sound/ambience/tbirds.wav
sound/ambience/wolfhowl02.wav
sound/ambience/3dmbridge.wav
sound/ambience/thunder.wav
sound/ambience/wind.wav
sound/ambience/crow.wav
sound/ambience/3dmwmill.wav
sound/ambience/burning3.wav
sound/ambience/cow.wav
sound/ambience/drips.wav
sprites/xffloor.spr
sprites/xspark4.spr
sprites/glow01.spr
sprites/snow.spr
sprites/xssmke1.spr
