maps/de_amazonas_beta.txt
maps/de_amazonas_beta.nav
gfx/env/rio_amazonasLF.tga
gfx/env/rio_amazonasDN.tga
gfx/env/rio_amazonasFT.tga
gfx/env/rio_amazonasBK.tga
gfx/env/rio_amazonasRT.tga
gfx/env/rio_amazonasUP.tga
models/amazonas/ave.mdl
models/amazonas/bandeira.mdl
models/amazonas/barris2.mdl
models/amazonas/barris.mdl
models/amazonas/bote.mdl
models/amazonas/capitao.mdl
models/amazonas/fio.mdl
models/amazonas/gerador.mdl
models/amazonas/helicoptero.mdl
models/amazonas/nada.mdl
sound/amazonas/10s.wav
sound/amazonas/ave.wav
sound/amazonas/bandolera.wav
sound/amazonas/bote.wav
sound/amazonas/fanfarrao.wav
sound/amazonas/muleque.wav
overviews/de_amazonas_beta.bmp
overviews/de_amazonas_beta.txt
