//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  : de_dustcity
//
// Download @: http://dwl.17buddies.net/link/map/2901/de_dustcity.html
//
//////////////////////////////////////////////////////////
kp-tex01.wad

gfx/env/Geozup.tga
gfx/env/Geozdn.tga
gfx/env/Geozlf.tga
gfx/env/Geozrt.tga
gfx/env/Geozft.tga
gfx/env/Geozbk.tga
 
sound/ambience/wind2.wav
sound/ambience/alienwind1.wav
sound/ambience/industrial1.wav
sound/ambience/mechwhine.wav
sound/ambience/pounder.wav

sprites/flare1.spr