gfx/env/skybox06_bk.tga
gfx/env/skybox06_dn.tga
gfx/env/skybox06_ft.tga
gfx/env/skybox06_lf.tga
gfx/env/skybox06_rt.tga
gfx/env/skybox06_up.tga
models/props/weaponsTableCT.mdl
models/props/weaponsTableTT.mdl
models/shrubbery/grass/grassbright-a.mdl
models/shrubbery/grass/grassbright-b.mdl
models/shrubbery/grass/grassshort-b.mdl
models/shrubbery/grass/grassshort-c.mdl
models/shrubbery/grass/grasstall-a.mdl
models/shrubbery/plants/arc_fern.mdl
models/shrubbery/plants/bush_fern_small_ground.mdl
models/shrubbery/plants/bush18.mdl
overviews/gsu_traindenment.bmp
overviews/gsu_traindenment.txt
sound/ambience/chainlink.wav
sound/ambience/.wav
sound/ambience/dry_air_short.wav
sound/ambience/light_hum.wav
sound/ambience/pipe_amb1.wav
sound/ambience/water_gentle1.wav
sprites/glow04.spr
sprites/rain_splash_01.spr
author.wad
traindenment3.wad