gfx/detail/dt_brick.tga
gfx/detail/dt_conc.tga
gfx/detail/dt_plaster1.tga
gfx/detail/dt_carpet1.tga
gfx/detail/dt_metal1.tga
gfx/detail/dt_smooth1.tga
maps/de_japan.bsp
maps/de_japan.res
maps/de_japan.txt
maps/de_japan_detail.txt
models/de_japan/jeep.mdl
models/can_japan_1.mdl
models/can_japan_2.mdl
models/can_japan_3.mdl
models/can_japan_4.mdl
models/can_japan_5.mdl
overviews/de_japan.bmp
overviews/de_japan.txt
sound/de_japan/beepslow.wav
sound/de_japan/city.wav
sound/de_japan/electric.wav
sound/de_japan/station.wav
sound/de_japan/wind.wav