sound/misc/multikill.wav 
sound/misc/ultrakill.wav 
sound/misc/killingspree.wav
sound/misc/monsterkill.wav 
sound/misc/godlike.wav 
sound/misc/ADICA.wav
sound/misc/alleluja.wav
sound/misc/ALO.wav
sound/misc/amor.wav
sound/misc/ani.wav
sound/misc/aplauze.wav
sound/misc/bastard.wav
sound/misc/Beleste+ochii.wav
sound/misc/bomba.wav
sound/misc/CAPCANA.wav
sound/misc/capitanul.wav
maps/de_train.res
maps/default.txt

