//////////////////////////////////////////////////////////
// Resources file, created with 17Ims, free software!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
gfx/env/ambush_up.tga
gfx/env/ambush_dn.tga
gfx/env/ambush_lf.tga
gfx/env/ambush_rt.tga
gfx/env/ambush_ft.tga
gfx/env/ambush_bk.tga
models/ambush/store_ledge.mdl
models/ambush/cola.mdl
models/ambush/cash_table.mdl
models/ambush/posters.mdl
models/ambush/pizza_kitchen.mdl
models/ambush/scar_mags.mdl
models/ambush/cl_winebtl2.mdl
models/ambush/cl_redwine_gls.mdl
models/ambush/scar_colt.mdl
models/ambush/cl_newspaper.mdl
models/ambush/pizza_furniture.mdl
models/ambush/cola_small.mdl
models/ambush/cash_table_b.mdl
models/ambush/shirts_shelves_brown.mdl
models/ambush/shirts_shelves_blood.mdl
models/ambush/shirts_shelves.mdl
models/ambush/shirts_stands.mdl
models/ambush/music_ledges_wall.mdl
sound/ambush/ambience1.wav
sound/ambush/ambience2.wav
models/ambush/shirts_shelves_orange.mdl
models/ambush/shirts_shelves_red.mdl
models/ambush/dailynews_storm.mdl
models/ambush/veg_palm04.mdl
models/ambush/scar_picture.mdl
models/ambush/vegkbplanter_am.mdl
models/ambush/phone.mdl
models/ambush/veg_agave_1amB.mdl
models/ambush/cl_mob_wine1.mdl
models/ambush/scar_chnsaw.mdl
models/ambush/veg_agave_2amB.mdl
models/ambush/veg_minipalm1am.mdl
models/ambush/sm_des_bush2.mdl
models/ambush/veg_agave_1am.mdl
models/ambush/sm_Agave_bloom.mdl
models/ambush/sm_des_bush1.mdl
sound/ambush/melody.wav
sound/ambush/espantoso.wav
sound/ambush/starr.wav
sound/ambush/indiner.wav
sound/ambush/treetouch.wav
models/ambush/veg_plants_a_am.mdl
models/ambush/veg_plants_b_am.mdl
models/ambush/scar_hanger.mdl
models/ambush/scar_tv.mdl
models/ambush/scar_phone.mdl
models/ambush/scar_vegetation.mdl
models/ambush/scar_chair.mdl
models/ambush/veg_agave_2am.mdl
models/ambush/glow_orange_strong.mdl
models/ambush/trash_box.mdl
models/ambush/cock.mdl
models/ambush/scar_camera.mdl
models/ambush/upt_fence.mdl
models/ambush/gta_pizzaboy.mdl
models/ambush/cz_bike.mdl
sound/ambush/flies.wav
models/ambush/vegyuka128_am.mdl
models/ambush/scar_sunray_board.mdl
models/ambush/gta3_tree_too.mdl
models/ambush/noodle_signboard.mdl
models/ambush/oldcar_stunt.mdl
models/ambush/sign_cafe.mdl
models/ambush/sign_diner.mdl
models/ambush/sign_shad2.mdl
models/ambush/sign_bailtshop.mdl
