gfx/env/dmcwbk.tga
gfx/env/dmcwdn.tga
gfx/env/dmcwft.tga
gfx/env/dmcwlf.tga
gfx/env/dmcwrt.tga
gfx/env/dmcwup.tga
models/dutch/tree/arc_bush.mdl
models/dutch/tree/arc_xer_tree1.mdl
models/dutch/tree/barbed_wire.mdl
models/dutch/tree/barrelcrash.mdl
models/dutch/tree/by_rubble_set.mdl
models/dutch/tree/car021.mdl
models/dutch/tree/dod_jagd_statue.mdl
models/dutch/tree/flo_tree04.mdl
models/dutch/tree/fueltruck.mdl
models/dutch/tree/hk_panzer4j_greyfull.mdl
models/dutch/tree/hk_sherman_damaged2.mdl
models/dutch/tree/sandbags.mdl
overviews/dm_dutchtown.bmp
overviews/dm_dutchtown.txt
sound/ambience/steamburst1.wav
sound/ambience/tankidle1.wav
sound/ambience/tankidle2.wav
sound/dutch/armybeach/sincity2.wav